# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  mp_server_config = debug
endif
ifeq ($(config),release)
  mp_server_config = release
endif
ifeq ($(config),dist)
  mp_server_config = dist
endif

PROJECTS := mp_server

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

mp_server:
ifneq (,$(mp_server_config))
	@echo "==== Building mp_server ($(mp_server_config)) ===="
	@${MAKE} --no-print-directory -C mp_server -f Makefile config=$(mp_server_config)
endif

clean:
	@${MAKE} --no-print-directory -C mp_server -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   mp_server"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"